### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by thespamer** [safe-global/safe-infrastructure#65]
I just create an AWS ec2 with safe-infrastructure with DNS already, but when I logged into my domain:

http://gnosis-test.asd.com:8000/cfg/admin/login/?next=/cfg/admin/chains/chain/add/ 

There is a Forbidden / CSRF verification failed. Request aborted.

There is any config for django and CSRF ?

Regards

**Comment by thespamer** [comment]
I saw on container_env_files/cfg.env:
CSRF_TRUSTED_ORIGINS="http://gnosis-test.asd.com:8000"

There is another place to place my own domain?

**Comment by comverser** [comment]
Same here

**Comment by comverser** [comment]
> I saw on container_env_files/cfg.env: CSRF_TRUSTED_ORIGINS="http://gnosis-test.asd.com:8000"
> 
> There is another place to set my own domain?

Modifying the `CSRF_TRUSTED_ORIGINS` parameter in `container_env_files/cfg.env` worked for me.

**Comment by mhxw** [comment]
This might solve your problem. https://github.com/safe-global/safe-transaction-service/issues/1225

**Comment by comverser** [comment]
> 

I found other modifications that are newer.
- https://github.com/safe-global/safe-infrastructure/issues/66
- https://github.com/safe-global/safe-infrastructure/issues/64

**Comment by hectorgomezv** [comment]
Hello @thespamer, I see your test setup is not online anymore. Did you solve the issue? The `CSRF_TRUSTED_ORIGINS` you wrote seems OK, but maybe another part of your infrastructure (some AWS firewall/API Gateway?) was masking the `Origin`/`Referer` field so the CSRF verification didn't pass. You'd need to check the `Host` saw by the service matches the `Origin`/`Referer` as explained in [the docs](https://docs.djangoproject.com/en/4.2/ref/settings/#csrf-trusted-origins).

If you managed to solve the issue, could you close it? (and if you found where the problem was, it would be really nice if you share it 🙂)
